version: '3'

services:

  backend:
      container_name: backend-alma
      build: .
      restart: always
      entrypoint: /bin/sh './scripts/be-node-dev.sh'
      env_file:
        - .env
      ports:
        - '3333:3333'
      depends_on:
        - db_postgres
      links:
        - db_postgres
      volumes:
        - .:/app/
        - ./nodemon.json:/app/nodemon.json


      
  db_postgres:
    container_name: 'postgres'
    image: 'postgres:14.2-alpine'
    restart: on-failure
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=alma
      - POSTGRES_PASSWORD=postgrespw
    # run ./scripts/db-init.sh to create the database on the first run
    volumes:
      - ./scripts/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh



 
    
