version: '3'

services:

  backend:
      container_name: backend-alma
      build: .
      restart: always
      entrypoint: /bin/sh './scripts/be-node-dev.sh'
      env_file:
        - .env
      ports:
        - '3333:3333'
      depends_on:
        - db_postgres
      links:
        - db_postgres
      volumes:
        - .:/app/
        - /app/node_modules

      
  db_postgres:
    container_name: 'postgres'
    image: 'postgres:14.2-alpine'
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'

 
    
